rules:
  - id: md5-usage
    languages:
      - kotlin
    message: Found md5 usage
    pattern: hashlib.md5(...)
    severity: HIGH
  - id: di-injections
    languages:
      - kotlin
    message: Wrong DI Injection
    pattern: |
      @Service
          class $CLASS {
              private val $FIELD = $FIELD()
          }
    severity: MEDIUM
  - id: thread-usage
    languages:
      - kotlin
    message: Found Thread Usage
    pattern: |
      @GetMapping
      fun $FUNC(): $RET {
        ...
        Thread.sleep(...)
        ...
    }
    severity: HIGH
  - id: empty-catch
    languages:
      - kotlin
    message: Found Empty Catch Block
    pattern: |
      try {
        ...
      } catch (e : Exception) {
      
      }
    severity: LOW
